### ISSUE TITLE
custom query parameter name for dynamic redirects

### ISSUE THREAD

**Issue by freddyshim** [Openscreen-Inc/openscreen-sdk-js#4]
Creating a QR code with “dynamicRedirectType = QrCodeDynamicRedirectType.SCAN_ID_IN_QUERY_STRING_PARAMETER” appends the scan ID to the intent URL (eg. example.com?scanId=abcdefg)

I want to change the “scanId” attribute to whatever value I want (eg. example.com?my-custom-attribute=abcdefg). Is this possible?

**Comment by NimishVerma** [comment]
#7 release v1.4.0 includes this feature.
